"""B6: the 2D QNEC as certified Schur-pivot positivity (conjecture ?2).

CENTRAL EXACT FACT (algebraic, proved by the Schur-complement lemma):
the strengthened 2D QNEC

    2 pi <T_++>  >=  S'' + (6/c) (S')^2

holds  <=>  the 2x2 real symmetric matrix

    M = [ [ c/6 ,        S'      ],
          [ S'  ,  2 pi T - S''  ] ]

is positive semidefinite, since PSD(M) <=> c/6 > 0 and the Schur pivot
(2 pi T - S'') - (S')^2/(c/6) >= 0, which IS the QNEC combination.
This is literally the verifier standard S2 = G22 - G02^2/G00 >= 0.
QNEC saturation <=> zero pivot <=> rank(M) = 1: the flat / rank-deficient
boundary, the same structure B1 exploits for forcing.

EPISTEMIC SCOPE (read before promoting anything):
- This module is an exact REFORMULATION plus certified INSTANCES, not a
  new proof of QNEC. Proofs: Wall (2011, free fields); Balakrishnan,
  Faulkner, Khandker, Wang (2017, general QFT via modular theory);
  2D vacuum-conformal saturation is standard CFT.
- Whether M is the Gram matrix omega(A_i^dagger A_j) of concrete
  operators (a GNS realization) is the remaining open item separating
  P from H for ?2.

Instances certified here:
  vacuum interval        -> SATURATED  (exact rational; rank 1, pivot 0)
  chiral coherent state  -> STRICT     (exact: entropy unchanged, pivot
                                        = 2 pi f'(u)^2 > 0)
  thermal state          -> SATURATED  (symbolic polynomial identity in
                                        x = coth(pi du / beta))
  fabricated violation   -> REJECTED   (exact negative-pivot witness)
"""

from fractions import Fraction
from typing import Dict, List, Tuple

from b2_process_solver.cexact import CF, hermitian_psd_certificate


# ---------------------------------------------------------------- matrix --

def qnec_matrix(c6: Fraction, Sp: Fraction, Q22: Fraction):
    """M = [[c/6, S'], [S', 2 pi T - S'']] with exact rational entries.
    Q22 must be the exact rational value of (2 pi T - S'') -- valid
    whenever 2 pi T is rationally representable (all T = 0 cases here)."""
    return [[CF(c6), CF(Sp)], [CF(Sp), CF(Q22)]]


def schur_pivot(c6: Fraction, Sp: Fraction, Q22: Fraction) -> Fraction:
    """The QNEC combination, computed independently of the PSD routine
    (used as a cross-check that pivot-of-M == QNEC combination)."""
    return Fraction(Q22) - Fraction(Sp) ** 2 / Fraction(c6)


def certify(c6, Sp, Q22) -> Dict:
    M = qnec_matrix(c6, Sp, Q22)
    status, pivots, rank = hermitian_psd_certificate(M)
    piv = schur_pivot(c6, Sp, Q22)
    if status == "NOT_PSD_CERTIFIED":
        verdict = "QNEC_VIOLATED (REJECTED)"
    elif rank == 1:
        verdict = "QNEC_SATURATED (rank-deficient boundary)"
    else:
        verdict = "QNEC_STRICT"
    return {"psd_status": status, "schur_pivots": [str(p) for p in pivots],
            "rank": rank, "qnec_combination": str(piv), "verdict": verdict}


# ------------------------------------------------- exact state instances --

def vacuum_interval(c: Fraction, du: Fraction) -> Tuple[Fraction, Fraction, Fraction]:
    """2D CFT vacuum, interval with null separation du, deform one
    endpoint along u. From S = (c/6) ln(du dv / eps^2):
        S'  =  c / (6 du)          (log differentiates to rational)
        S'' = -c / (6 du^2)
        T   =  0
    Returns (c/6, S', 2 pi T - S'') -- all exact rationals."""
    c, du = Fraction(c), Fraction(du)
    c6 = c / 6
    Sp = c / (6 * du)
    Q22 = c / (6 * du ** 2)          # = 0 - S'' = +c/(6 du^2)
    return c6, Sp, Q22


def coherent_state(c: Fraction, du: Fraction, fprime: Fraction) -> Dict:
    """Chiral coherent state of a free boson on top of the vacuum:
    entanglement entropy is UNCHANGED (coherent states are related to the
    vacuum by a unitary generated by a linear field displacement, which
    acts locally on each side of the cut), while the stress tensor shifts
    by the classical piece  T_cl = (f'(u))^2  (in our normalization).

    The pivot splits exactly:
        pivot = 2 pi (f')^2 + [ (-S'') - (S')^2/(c/6) ]_vacuum
    and the vacuum bracket is EXACTLY ZERO (certified below), so the
    QNEC verdict is carried entirely by the rational number (f')^2 >= 0,
    with strictness iff f' != 0. The transcendental 2 pi multiplies a
    certified-sign rational and never needs numerical evaluation."""
    c6, Sp, Q22_vac = vacuum_interval(c, du)
    vacuum_bracket = schur_pivot(c6, Sp, Q22_vac)      # must be exactly 0
    strict_part = Fraction(fprime) ** 2
    verdict = ("QNEC_STRICT" if strict_part > 0 else
               "QNEC_SATURATED (rank-deficient boundary)")
    return {"vacuum_bracket_exact": str(vacuum_bracket),
            "vacuum_bracket_is_zero": vacuum_bracket == 0,
            "pivot": f"2*pi*{strict_part} + {vacuum_bracket}",
            "strict_part_rational": str(strict_part),
            "verdict": verdict}


# --------------------------------------------- symbolic thermal identity --

def thermal_identity_poly() -> List[Fraction]:
    """Thermal 2D CFT on a line at inverse temperature beta. With
    x = coth(pi du / beta):
        S'   =  (c pi / 6 beta) x
        S''  = -(c pi^2 / 6 beta^2) (x^2 - 1)      [csch^2 = x^2 - 1]
        2piT =  (c pi^2 / 6 beta^2)                [<T_uu> = pi c / 12 beta^2]
    QNEC combination, in units of (c pi^2 / 6 beta^2):
        Q(x) = 1 + (x^2 - 1) - x^2
    Returns the coefficient list [a0, a1, a2] of Q(x); the identity is
    certified iff every coefficient is exactly zero -- saturation for ALL
    interval sizes and temperatures at once (symbolic, not sampled)."""
    twoPiT = [Fraction(1), Fraction(0), Fraction(0)]     # 1
    minusSpp = [Fraction(-1), Fraction(0), Fraction(1)]  # x^2 - 1
    minusS6c = [Fraction(0), Fraction(0), Fraction(-1)]  # -(x^2)
    return [twoPiT[k] + minusSpp[k] + minusS6c[k] for k in range(3)]


# ------------------------------------------------------ negative control --

def fabricated_violation(c: Fraction, du: Fraction) -> Tuple[Fraction, Fraction, Fraction]:
    """A 'state' claiming vacuum energy (T = 0) but entropy growing with
    the WRONG concavity: S'' = +c/(6 du^2) (sign flipped). Then
    2 pi T - S'' = -c/(6 du^2) < 0 and the matrix must be rejected with
    an exact witness. Physically: entropy cannot accelerate along a null
    ray without paying energy -- the QNEC gate catching a fake."""
    c, du = Fraction(c), Fraction(du)
    return c / 6, c / (6 * du), -c / (6 * du ** 2)
